server:
  port: 8081

spring:
  application:
    name: ms-usuarios
  datasource:
    # URL de Amazon RDS, usa variables de entorno
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/${RDS_DB_NAME:certifika2}
    username: ${RDS_USERNAME:postgres}
    password: ${RDS_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
